#!/usr/bin/ruby
require "gtk3"

win = Gtk::Window.new
grid = Gtk::Grid.new
win.set_title("Grid Example")

button1 = Gtk::Button.new(:label => "Button 1")
button2 = Gtk::Button.new(:label => "Button 2")
button3 = Gtk::Button.new(:label => "Button 3")
button4 = Gtk::Button.new(:label => "Button 4")
button5 = Gtk::Button.new(:label => "Button 5")
button6 = Gtk::Button.new(:label => "Button 6")


grid.add(button1)
grid.attach(button2, 1, 0, 2, 1)
grid.attach_next_to(button3, button1, Gtk::PositionType::BOTTOM, 1, 2)
grid.attach_next_to(button4, button3, Gtk::PositionType::RIGHT, 2, 1)
grid.attach(button5, 1, 2, 1, 1)
grid.attach_next_to(button6, button5, Gtk::PositionType::RIGHT, 1, 1)

win.add(grid)
win.signal_connect("destroy"){Gtk.main_quit}
win.show_all
Gtk.main
